create table countries
(
    code varchar(3) primary key,
    country_name varchar (255)
);
INSERT INTO countries ("code","country_name") values ('ABH','Абхазия');
INSERT INTO countries ("code","country_name") values ('ABW','Аруба');
INSERT INTO countries ("code","country_name") values ('AFG','Афганистан');
INSERT INTO countries ("code","country_name") values ('AGO','Ангола');
INSERT INTO countries ("code","country_name") values ('AIA','Ангилья');
INSERT INTO countries ("code","country_name") values ('ALA','Эландские острова');
INSERT INTO countries ("code","country_name") values ('ALB','Албания');
INSERT INTO countries ("code","country_name") values ('AND','Андорра');
INSERT INTO countries ("code","country_name") values ('ARE','Объединенные Арабские Эмираты');
INSERT INTO countries ("code","country_name") values ('ARG','Аргентина');
INSERT INTO countries ("code","country_name") values ('ARM','Армения');
INSERT INTO countries ("code","country_name") values ('ASM','Американское Самоа');
INSERT INTO countries ("code","country_name") values ('ATA','Антарктида');
INSERT INTO countries ("code","country_name") values ('ATF','Французские Южные территории');
INSERT INTO countries ("code","country_name") values ('ATG','Антигуа и Барбуда');
INSERT INTO countries ("code","country_name") values ('AUS','Австралия');
INSERT INTO countries ("code","country_name") values ('AUT','Австрия');
INSERT INTO countries ("code","country_name") values ('AZE','Азербайджан');
INSERT INTO countries ("code","country_name") values ('BDI','Бурунди');
INSERT INTO countries ("code","country_name") values ('BEL','Бельгия');
INSERT INTO countries ("code","country_name") values ('BEN','Бенин');
INSERT INTO countries ("code","country_name") values ('BFA','Буркина-Фасо');
INSERT INTO countries ("code","country_name") values ('BGD','Бангладеш');
INSERT INTO countries ("code","country_name") values ('BGR','Болгария');
INSERT INTO countries ("code","country_name") values ('BHR','Бахрейн');
INSERT INTO countries ("code","country_name") values ('BHS','Багамы');
INSERT INTO countries ("code","country_name") values ('BIH','Босния и Герцеговина');
INSERT INTO countries ("code","country_name") values ('BLM','Сен-Бартелеми');
INSERT INTO countries ("code","country_name") values ('BLR','Беларусь');
INSERT INTO countries ("code","country_name") values ('BLZ','Белиз');
INSERT INTO countries ("code","country_name") values ('BMU','Бермуды');
INSERT INTO countries ("code","country_name") values ('BOL','Боливия, Многонациональное Государство');
INSERT INTO countries ("code","country_name") values ('BRA','Бразилия');
INSERT INTO countries ("code","country_name") values ('BRB','Барбадос');
INSERT INTO countries ("code","country_name") values ('BRN','Бруней-Даруссалам');
INSERT INTO countries ("code","country_name") values ('BTN','Бутан');
INSERT INTO countries ("code","country_name") values ('BVT','Остров Буве');
INSERT INTO countries ("code","country_name") values ('BWA','Ботсвана');
INSERT INTO countries ("code","country_name") values ('CAF','Центрально-Африканская Республика');
INSERT INTO countries ("code","country_name") values ('CAN','Канада');
INSERT INTO countries ("code","country_name") values ('CCK','Кокосовые (Килинг) острова');
INSERT INTO countries ("code","country_name") values ('CHE','Швейцария');
INSERT INTO countries ("code","country_name") values ('CHL','Чили');
INSERT INTO countries ("code","country_name") values ('CHN','Китай');
INSERT INTO countries ("code","country_name") values ('CIV', 'Кот д Ивуар');
INSERT INTO countries ("code","country_name") values ('CMR','Камерун');
INSERT INTO countries ("code","country_name") values ('COD','Конго, демократическая республика');
INSERT INTO countries ("code","country_name") values ('COG','Конго');
INSERT INTO countries ("code","country_name") values ('COK','Острова Кука');
INSERT INTO countries ("code","country_name") values ('COL','Колумбия');
INSERT INTO countries ("code","country_name") values ('COM','Коморы');
INSERT INTO countries ("code","country_name") values ('CPV','Кабо-Верде');
INSERT INTO countries ("code","country_name") values ('CRI','Коста-Рика');
INSERT INTO countries ("code","country_name") values ('CUB','Куба');
INSERT INTO countries ("code","country_name") values ('CUW','Кюрасао');
INSERT INTO countries ("code","country_name") values ('CXR','Остров Рождества');
INSERT INTO countries ("code","country_name") values ('CYM','Острова Кайман');
INSERT INTO countries ("code","country_name") values ('CYP','Кипр');
INSERT INTO countries ("code","country_name") values ('CZE','Чехия');
INSERT INTO countries ("code","country_name") values ('DEU','Германия');
INSERT INTO countries ("code","country_name") values ('DJI','Джибути');
INSERT INTO countries ("code","country_name") values ('DMA','Доминика');
INSERT INTO countries ("code","country_name") values ('DNK','Дания');
INSERT INTO countries ("code","country_name") values ('DOM','Доминиканская Республика');
INSERT INTO countries ("code","country_name") values ('DZA','Алжир');
INSERT INTO countries ("code","country_name") values ('ECU','Эквадор');
INSERT INTO countries ("code","country_name") values ('EGY','Египет');
INSERT INTO countries ("code","country_name") values ('ERI','Эритрея');
INSERT INTO countries ("code","country_name") values ('ESH','Западная Сахара');
INSERT INTO countries ("code","country_name") values ('ESP','Испания');
INSERT INTO countries ("code","country_name") values ('EST','Эстония');
INSERT INTO countries ("code","country_name") values ('ETH','Эфиопия');
INSERT INTO countries ("code","country_name") values ('FIN','Финляндия');
INSERT INTO countries ("code","country_name") values ('FJI','Фиджи');
INSERT INTO countries ("code","country_name") values ('FLK','Фолклендские острова (Мальвинские');
INSERT INTO countries ("code","country_name") values ('FRA','Франция');
INSERT INTO countries ("code","country_name") values ('FRO','Фарерские острова');
INSERT INTO countries ("code","country_name") values ('FSM','Микронезия, федеративные штаты');
INSERT INTO countries ("code","country_name") values ('GAB','Габон');
INSERT INTO countries ("code","country_name") values ('GBR','Соединенное Королевство');
INSERT INTO countries ("code","country_name") values ('GEO','Грузия');
INSERT INTO countries ("code","country_name") values ('GGY','Гернси');
INSERT INTO countries ("code","country_name") values ('GHA','Гана');
INSERT INTO countries ("code","country_name") values ('GIB','Гибралтар');
INSERT INTO countries ("code","country_name") values ('GIN','Гвинея');
INSERT INTO countries ("code","country_name") values ('GLP','Гваделупа');
INSERT INTO countries ("code","country_name") values ('GMB','Исламская Республика Гамбия');
INSERT INTO countries ("code","country_name") values ('GNB','Гвинея-Бисау');
INSERT INTO countries ("code","country_name") values ('GNQ','Экваториальная Гвинея');
INSERT INTO countries ("code","country_name") values ('GRC','Греция');
INSERT INTO countries ("code","country_name") values ('GRD','Гренада');
INSERT INTO countries ("code","country_name") values ('GRL','Гренландия');
INSERT INTO countries ("code","country_name") values ('GTM','Гватемала');
INSERT INTO countries ("code","country_name") values ('GUF','Французская Гвиана');
INSERT INTO countries ("code","country_name") values ('GUM','Гуам');
INSERT INTO countries ("code","country_name") values ('GUY','Кооперативная Республика Гайана');
INSERT INTO countries ("code","country_name") values ('HKG','Гонконг');
INSERT INTO countries ("code","country_name") values ('HMD','Остров Херд и острова Макдональд');
INSERT INTO countries ("code","country_name") values ('HND','Гондурас');
INSERT INTO countries ("code","country_name") values ('HRV','Хорватия');
INSERT INTO countries ("code","country_name") values ('HTI','Гаити');
INSERT INTO countries ("code","country_name") values ('HUN','Венгрия');
INSERT INTO countries ("code","country_name") values ('IDN','Индонезия');
INSERT INTO countries ("code","country_name") values ('IMN','Остров Мэн');
INSERT INTO countries ("code","country_name") values ('IND','Индия');
INSERT INTO countries ("code","country_name") values ('IOT','Британская территория в Индийском океане');
INSERT INTO countries ("code","country_name") values ('IRL','Ирландия');
INSERT INTO countries ("code","country_name") values ('IRN','Иран, исламская республика');
INSERT INTO countries ("code","country_name") values ('IRQ','Ирак');
INSERT INTO countries ("code","country_name") values ('ISL','Исландия');
INSERT INTO countries ("code","country_name") values ('ISR','Израиль');
INSERT INTO countries ("code","country_name") values ('ITA','Италия');
INSERT INTO countries ("code","country_name") values ('JAM','Ямайка');
INSERT INTO countries ("code","country_name") values ('JEY','Джерси');
INSERT INTO countries ("code","country_name") values ('JOR','Иордания');
INSERT INTO countries ("code","country_name") values ('JPN','Япония');
INSERT INTO countries ("code","country_name") values ('KAZ','Казахстан');
INSERT INTO countries ("code","country_name") values ('KEN','Кения');
INSERT INTO countries ("code","country_name") values ('KGZ','Киргизия');
INSERT INTO countries ("code","country_name") values ('KHM','Камбоджа');
INSERT INTO countries ("code","country_name") values ('KIR','Кирибати');
INSERT INTO countries ("code","country_name") values ('KNA','Сент-Китс и Невис');
INSERT INTO countries ("code","country_name") values ('KOR','Корея, республика');
INSERT INTO countries ("code","country_name") values ('KWT','Кувейт');
INSERT INTO countries ("code","country_name") values ('LAO','Лаосская Народно-Демократическая Республика');
INSERT INTO countries ("code","country_name") values ('LBN','Ливан');
INSERT INTO countries ("code","country_name") values ('LBR','Либерия');
INSERT INTO countries ("code","country_name") values ('LBY','Государство Ливия');
INSERT INTO countries ("code","country_name") values ('LCA','Сент-Люсия');
INSERT INTO countries ("code","country_name") values ('LIE','Лихтенштейн');
INSERT INTO countries ("code","country_name") values ('LKA','Шри-Ланка');
INSERT INTO countries ("code","country_name") values ('LSO','Лесото');
INSERT INTO countries ("code","country_name") values ('LTU','Литва');
INSERT INTO countries ("code","country_name") values ('LUX','Люксембург');
INSERT INTO countries ("code","country_name") values ('LVA','Латвия');
INSERT INTO countries ("code","country_name") values ('MAC','Макао');
INSERT INTO countries ("code","country_name") values ('MАF','Сен-Мартен (французская часть');
INSERT INTO countries ("code","country_name") values ('MAR','Марокко');
INSERT INTO countries ("code","country_name") values ('MCO','Монако');
INSERT INTO countries ("code","country_name") values ('MDA','Молдова, республика');
INSERT INTO countries ("code","country_name") values ('MDG','Мадагаскар');
INSERT INTO countries ("code","country_name") values ('MDV','Мальдивы');
INSERT INTO countries ("code","country_name") values ('MEX','Мексика');
INSERT INTO countries ("code","country_name") values ('MHL','Маршалловы Острова');
INSERT INTO countries ("code","country_name") values ('MKD','Северная Македония');
INSERT INTO countries ("code","country_name") values ('MLI','Мали');
INSERT INTO countries ("code","country_name") values ('MLT','Мальта');
INSERT INTO countries ("code","country_name") values ('MMR','Мьянма');
INSERT INTO countries ("code","country_name") values ('MNE','Черногория');
INSERT INTO countries ("code","country_name") values ('MNG','Монголия');
INSERT INTO countries ("code","country_name") values ('MNP','Северные Марианские острова');
INSERT INTO countries ("code","country_name") values ('MOZ','Мозамбик');
INSERT INTO countries ("code","country_name") values ('MRT','Мавритания');
INSERT INTO countries ("code","country_name") values ('MSR','Монтсеррат');
INSERT INTO countries ("code","country_name") values ('MTQ','Мартиника');
INSERT INTO countries ("code","country_name") values ('MUS','Маврикий');
INSERT INTO countries ("code","country_name") values ('MWI','Малави');
INSERT INTO countries ("code","country_name") values ('MYS','Малайзия');
INSERT INTO countries ("code","country_name") values ('MYT','Майотта');
INSERT INTO countries ("code","country_name") values ('NAM','Намибия');
INSERT INTO countries ("code","country_name") values ('NCL','Новая Каледония');
INSERT INTO countries ("code","country_name") values ('NER','Нигер');
INSERT INTO countries ("code","country_name") values ('NFK','Остров Норфолк');
INSERT INTO countries ("code","country_name") values ('NGA','Нигерия');
INSERT INTO countries ("code","country_name") values ('NIC','Никарагуа');
INSERT INTO countries ("code","country_name") values ('NIU','Ниуэ');
INSERT INTO countries ("code","country_name") values ('NLD','Нидерланды');
INSERT INTO countries ("code","country_name") values ('NOR','Норвегия');
INSERT INTO countries ("code","country_name") values ('NPL','Непал');
INSERT INTO countries ("code","country_name") values ('NRU','Науру');
INSERT INTO countries ("code","country_name") values ('NZL','Новая Зеландия');
INSERT INTO countries ("code","country_name") values ('OMN','Оман');
INSERT INTO countries ("code","country_name") values ('OST','Южная Осетия');
INSERT INTO countries ("code","country_name") values ('PAK','Пакистан');
INSERT INTO countries ("code","country_name") values ('PAN','Панама');
INSERT INTO countries ("code","country_name") values ('PCN','Питкерн');
INSERT INTO countries ("code","country_name") values ('PER','Перу');
INSERT INTO countries ("code","country_name") values ('PHL','Филиппины');
INSERT INTO countries ("code","country_name") values ('PLW','Палау');
INSERT INTO countries ("code","country_name") values ('PNG','Папуа Новая Гвинея');
INSERT INTO countries ("code","country_name") values ('POL','Польша');
INSERT INTO countries ("code","country_name") values ('PRI','Пуэрто-Рико');
INSERT INTO countries ("code","country_name") values ('PRK','Корея, народно-демократическая республика');
INSERT INTO countries ("code","country_name") values ('PRT','Португалия');
INSERT INTO countries ("code","country_name") values ('PRY','Парагвай');
INSERT INTO countries ("code","country_name") values ('PSE','Палестина, государство');
INSERT INTO countries ("code","country_name") values ('PYF','Французская Полинезия');
INSERT INTO countries ("code","country_name") values ('QAT','Катар');
INSERT INTO countries ("code","country_name") values ('REU','Реюньон');
INSERT INTO countries ("code","country_name") values ('ROU','Румыния');
INSERT INTO countries ("code","country_name") values ('RUS','Россия');
INSERT INTO countries ("code","country_name") values ('RWA','Руанда');
INSERT INTO countries ("code","country_name") values ('SAU','Саудовская Аравия');
INSERT INTO countries ("code","country_name") values ('SDN','Судан');
INSERT INTO countries ("code","country_name") values ('SEN','Сенегал');
INSERT INTO countries ("code","country_name") values ('SGP','Сингапур');
INSERT INTO countries ("code","country_name") values ('SGS','Южная Джорджия и Южные Сандвичевы острова');
INSERT INTO countries ("code","country_name") values ('SHN','Святая Елена, остров Вознесения, Тристан-да-Кунья');
INSERT INTO countries ("code","country_name") values ('SJM','Шпицберген и Ян Майен');
INSERT INTO countries ("code","country_name") values ('SLB','Соломоновы Острова');
INSERT INTO countries ("code","country_name") values ('SLE','Сьерра-Леоне');
INSERT INTO countries ("code","country_name") values ('SLV','Эль-Сальвадор');
INSERT INTO countries ("code","country_name") values ('SMR','Сан-Марино');
INSERT INTO countries ("code","country_name") values ('SOM','Сомали');
INSERT INTO countries ("code","country_name") values ('SPM','Сент-Пьер и Микелон');
INSERT INTO countries ("code","country_name") values ('SRB','Сербия');
INSERT INTO countries ("code","country_name") values ('SSD','Южный Судан');
INSERT INTO countries ("code","country_name") values ('STP','Сан-Томе и Принсипи');
INSERT INTO countries ("code","country_name") values ('SUR','Суринам');
INSERT INTO countries ("code","country_name") values ('SVK','Словакия');
INSERT INTO countries ("code","country_name") values ('SVN','Словения');
INSERT INTO countries ("code","country_name") values ('SWE','Швеция');
INSERT INTO countries ("code","country_name") values ('SWZ','Эсватини');
INSERT INTO countries ("code","country_name") values ('SXM','Сен-Мартен (нидерландская часть');
INSERT INTO countries ("code","country_name") values ('SYC','Сейшелы');
INSERT INTO countries ("code","country_name") values ('SYR','Сирийская Арабская Республика');
INSERT INTO countries ("code","country_name") values ('TCA','Острова Теркс и Кайкос');
INSERT INTO countries ("code","country_name") values ('TCD','Чад');
INSERT INTO countries ("code","country_name") values ('TGO','Того');
INSERT INTO countries ("code","country_name") values ('THA','Таиланд');
INSERT INTO countries ("code","country_name") values ('TJK','Таджикистан');
INSERT INTO countries ("code","country_name") values ('TKL','Токелау');
INSERT INTO countries ("code","country_name") values ('TKM','Туркмения');
INSERT INTO countries ("code","country_name") values ('TLS','Тимор-Лесте');
INSERT INTO countries ("code","country_name") values ('TON','Тонга');
INSERT INTO countries ("code","country_name") values ('TTO','Тринидад и Тобаго');
INSERT INTO countries ("code","country_name") values ('TUN','Тунис');
INSERT INTO countries ("code","country_name") values ('TUR','Турция');
INSERT INTO countries ("code","country_name") values ('TUV','Тувалу');
INSERT INTO countries ("code","country_name") values ('TWN','Тайвань (Китай');
INSERT INTO countries ("code","country_name") values ('TZA','Танзания, объединенная республика');
INSERT INTO countries ("code","country_name") values ('UGA','Уганда');
INSERT INTO countries ("code","country_name") values ('UKR','Украина');
INSERT INTO countries ("code","country_name") values ('UMI','Малые Тихоокеанские Отдаленные острова Соединенных Штатов');
INSERT INTO countries ("code","country_name") values ('URY','Уругвай');
INSERT INTO countries ("code","country_name") values ('USA','Соединенные Штаты');
INSERT INTO countries ("code","country_name") values ('UZB','Узбекистан');
INSERT INTO countries ("code","country_name") values ('VAT','Папский Престол (Государство - город Ватикан');
INSERT INTO countries ("code","country_name") values ('VCT','Сент-Винсент и Гренадины');
INSERT INTO countries ("code","country_name") values ('VEN','Венесуэла Боливарианская Республика');
INSERT INTO countries ("code","country_name") values ('VGB','Виргинские острова, Британские');
INSERT INTO countries ("code","country_name") values ('VIR','Виргинские острова, США');
INSERT INTO countries ("code","country_name") values ('VNM','Вьетнам');
INSERT INTO countries ("code","country_name") values ('VUT','Вануату');
INSERT INTO countries ("code","country_name") values ('WLF','Уоллис и Футуна');
INSERT INTO countries ("code","country_name") values ('WSM','Самоа');
INSERT INTO countries ("code","country_name") values ('YEM','Йемен');
INSERT INTO countries ("code","country_name") values ('ZAF','Южная Африка');
INSERT INTO countries ("code","country_name") values ('ZMB','Замбия');
INSERT INTO countries ("code","country_name") values ('ZWE','Зимбабве');